theme: jekyll-theme-minimal
title: ".NET Presentations: Events in a Box!"
description: "This is the home repo for .NET Presentations, with a listing of workshops and presentations you can both use and contribute to."
show_downloads: true
